### ISSUE TITLE
Table formatting in Crystal documentation

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11899]
Since Crystal's docs generator supports full CommonMark, it is theoretically possible to include HTML tables in documentation, but they are unformatted right now:

```crystal
# <table>
# <tr><th>foo</th><th>bar</th></tr>
# <tr><td>3</td><td>4</td></tr>
# <tr><td>5</td><td>6</td></tr>
# </table>
def foo
end
```

![Screenshot_20220315_033328](https://user-images.githubusercontent.com/1361918/158247383-babbca02-63a9-4145-adef-4400333897f1.png)

Maybe we should add some CSS rules in anticipation of them?

An alternative is to use GitHub-flavored Markdown tables, especially if third-party docs generators are used, but they are not supported by markd at the moment. The current convention in the standard library is `text` code blocks, but the tables themselves do not follow any particular format:

https://github.com/crystal-lang/crystal/blob/e74a34b1a27f7588f9d49f6aa7f4688e29448ab5/src/kernel.cr#L174-L182

https://github.com/crystal-lang/crystal/blob/e74a34b1a27f7588f9d49f6aa7f4688e29448ab5/src/int.cr#L93-L99

https://github.com/crystal-lang/crystal/blob/e74a34b1a27f7588f9d49f6aa7f4688e29448ab5/src/file.cr#L90-L109

(To be fair, these are the _only_ tables in the standard library's documentation, however I don't see any particular reason to avoid them.)

I think it is a good idea to ensure that these tables are valid GFM tables, even if they are not displayed as such at the moment. Perhaps there is some kind of magic to mark them as code blocks for our generator but regular Markdown for other generators.

**Comment by straight-shoota** [comment]
Ref: https://github.com/icyleaf/markd/issues/4

**Comment by fdocr** [comment]
I found this issue after I noticed tables aren't supported from a README ([here](https://github.com/fdocr/CrystalSnake#deployment)) vs output docs ([here](https://fdocr.github.io/CrystalSnake/index.html#deployment)). Just wanted to mention that this feature would likely fix this even if not using them on inline comments. Also wanted to subscribe to the thread for future updates on the topic too 🙂

**Comment by nobodywasishere** [comment]
I found this CSS worked well for tables. I can create a PR if this works.

```css
table {
  font-size: 14px;
  display: block;
  max-width: -moz-fit-content;
  max-width: fit-content;
  overflow-x: auto;
  white-space: nowrap;
  background: #fdfdfd;
  text-align: center;
  border: 1px solid #eee;
  border-collapse: collapse;
  padding: 0px 5px 0px 5px;
}

table th {
  padding: 10px;
  letter-spacing: 1px;
  border-bottom: 1px solid #eee;
}

table td {
  padding: 10px;
}

<!-- in dark mode query -->

pre,
table {
  color: white;
  background: #202020;
  border: 1px solid #353535;
}

table th {
  border-bottom: 1px solid #353535;
}
```

![image](https://github.com/crystal-lang/crystal/assets/32797552/ef6c675b-0fe3-49ea-bc44-c70c52485e36)

![image](https://github.com/crystal-lang/crystal/assets/32797552/18f90401-5990-4aae-8cca-e931aa92b822)
