### ISSUE TITLE
'String' shift state specs fail on FreeBSD due to iconv differences

### ISSUE THREAD

**Issue by dmgk** [crystal-lang/crystal#12338]
New BIG5-HKSCS shift state tests introduced by https://github.com/crystal-lang/crystal/commit/d0b2b08f4b254350881bc06957249800c9853b35 currently do not pass on FreeBSD:

```
Failures:

  1) String encode decodes with shift state
     Failure/Error: {% unless flag?(:without_iconv) %}

       Expected: "Ê̄"
            got: "\uF325"

     # spec/std/string_spec.cr:2668
```

Looking at [Hong Kong Supplementary Character Set - 2008](https://www.ccli.gov.hk/doc/e_hkscs_2008.pdf), it appears that FreeBSD iconv encoder expects ISO/IEC 10646 compatibility code points, and the decoder returns ISO/IEC 10646-1:2000. I.e. (see https://github.com/crystal-lang/crystal/issues/11992)

- `0x8866` is encoded from `0xF329`, not from `0x00CA` (`0x00CA` gives "Invalid multibyte sequence")
- `0x8862` is encoded from `0xF325`, not from `0x00CA 0x0304`

and

- `0x8862` decodes to `0xF325`, not to `0x00CA 0x0304`

I'm not sure where this difference is coming from. FreeBSD uses Citrus iconv, perhaps they implement some older HKSCS standard.
