### ISSUE TITLE
Serialise to YAML with comments 

### ISSUE THREAD

**Issue by BigBoyBarney** [crystal-lang/crystal#15281]
*Parsing* / *deserialising* YAML with comments will throw them away due to `libyaml` skipping them. However, we could still have comment *serialisation*, which would be very useful for config files that are intended to be edited by the user.

I propose a new `YAML::Field` for `YAML::Serializable`.
Example:
```cr
struct Config
  include ::YAML::Serializable

  @[YAML::Field(converter: Time::EpochConverter, comment: "Unix time of the last update")]
  property last_update : Time = Time.utc.to_unix

  @[YAML::Field(comment: "Update interval in days")]
  property update_interval : Int32 = 7

  property sources : Array(String) = ["1", "2"]
end
```
would result in:
```yaml
---
# Unix time of the last update
last_update: 1734177189
# Update interval in days
update_interval: 7
sources:
- 1
- 2
```

I think this would fit into the module quite well, and annotations could potentially be used for deserialising as well if it's ever implemented in the future.
