### ISSUE TITLE
Can't append to file on windows without blocking

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#15680]
While we can read and write to files asynchronously on Windows (by passing `blocking: false` so `FILE_FLAG_OVERLAPPED` is set), trying to append to an existing file will actually overwrite the file.

The following example is an extract from `spec/std/file_spec.cr` that reproduces the problem:

```crystal
path = "append.txt"

File.write(path, "hello", blocking: false)
p File.read(path, blocking: false)
# => "hello"

File.write(path, " world", mode: "a", blocking: false)
p File.read(path, blocking: false)
# => " world"
```

**Comment by ysbaddaden** [comment]
I guess this is related to https://github.com/crystal-lang/crystal/blob/master/src/crystal/system/win32/file.cr#L60-L62

**Comment by ysbaddaden** [comment]
File spec failures when I try to make `File` read and write asynchronously by default on Windows:

```
Failures:

  1) File write can append to an existing file
     Failure/Error: File.read(path).should eq("hello world")

       Expected: "hello world"
            got: " world"

     # spec\std\file_spec.cr:876

  2) File supports the `b` mode flag
     Failure/Error: bytes.should eq(Bytes[1, 3, 6, 10, 13, 13, 10])

       Expected: Bytes[1, 3, 6, 10, 13, 13, 10]
            got: Bytes[13, 13, 10, 10, 0, 0, 0]

     # spec\std\file_spec.cr:942

  3) File returns the actual position with tell after append
     Failure/Error: file.tell.should eq(10)

       Expected: 10
            got: 5

     # spec\std\file_spec.cr:1021

  4) File does not overwrite existing content in append mode
     Failure/Error: File.read(filename).should eq "0123456789abcd"

       Expected: "0123456789abcd"
            got: "01234abcd9"

     # spec\std\file_spec.cr:1035
```
