### ISSUE TITLE
[travis] nightly build gets stuck on [Y/N] prompt

### ISSUE THREAD

**Issue by waterlink** [crystal-lang/crystal#2400]
The relevant config looks like this:

```yaml
sudo: required
dist: trusty

language: crystal
crystal:
  - nightly
```

Example failing build: https://travis-ci.org/trapped/sqlite_adapter.cr/builds/120331175
