### ISSUE TITLE
Markdown parser mangles codeblocks placed immediately after a list

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3772]
Failing test showing buggy behaviour:

```diff
diff --git a/spec/std/markdown/markdown_spec.cr b/spec/std/markdown/markdown_spec.cr
index 33fea905e..270ea324f 100644
--- a/spec/std/markdown/markdown_spec.cr
+++ b/spec/std/markdown/markdown_spec.cr
@@ -79,6 +79,7 @@ describe Markdown do
   assert_render "* Level1\n  * Level2\n  * Level2", "<ul><li>Level1</li><ul><li>Level2</li><li>Level2</li></ul></ul>"
   assert_render "* Hello\nWorld", "<ul><li>Hello\nWorld</li></ul>"
   assert_render "Params:\n* Foo\n* Bar", "<p>Params:</p>\n\n<ul><li>Foo</li><li>Bar</li></ul>"
+  assert_render "* Hello\n* World\n\n```\nHello World\n```", "<ul><li>Hello</li><li>World</li></ul>\n\n<pre><code>Hello World</code></pre>"

   assert_render "+ Hello", "<ul><li>Hello</li></ul>"
   assert_render "- Hello", "<ul><li>Hello</li></ul>"
```

Running `crystal spec spec/std/markdown/markdown_spec.cr` results in:
```
Failures:

  1) Markdown renders "* Hello\n* World\n\n```\nHello World\n```"
     Failure/Error: assert_render "* Hello\n* World\n\n```\nHello World\n```", "<ul><li>Hello</li><li>World</li></ul>\n\n<pre><code>Hello World</code></pre>"

       expected: "<ul><li>Hello</li><li>World</li></ul>\n\n<pre><code>Hello World</code></pre>"
            got: "<ul><li>Hello</li><li>World</li></ul>\n\n<pre><code class='language-Hello World'>```</code></pre>"

     # spec/std/markdown/markdown_spec.cr:82
```

This issue has been filled as a followup to https://github.com/crystal-lang/crystal/pull/3759#issuecomment-269038209.
