### ISSUE TITLE
Broken meta-model above Reference (Why "Object == Class" answers true) (Original: [Metamodel] Superclass of Reference is mismatched)

### ISSUE THREAD

**Issue by david50407** [crystal-lang/crystal#3874]
When I'm working on #3871 for creating the macro of getting the superclasses/ancestors of a Type, I found that if I run the code below, that will show the superclass of `Reference` is `Class`:

```crystal
class Reference
  def self.superclass
    {{@type.superclass}}
  end
end

puts Reference.superclass #=> Class
```

But this is mismatched with the [API document](https://crystal-lang.org/api/0.20.4/Reference.html) which tells that `Reference` is inherited from `Object`

And more, if I change the spec of superclass macro into this, it gives me `Reference`'s supeerclass is `Object`!?

```crystal
it "executes superclass" do
  assert_macro("x", "{{x.superclass}}", %(Reference)) do |program|
    # original: [TypeNode.new(program.string)] of ASTNode
    [TypeNode.new(program.reference)] of ASTNode
  end
end
```

```
Failures:

  1) macro methods type methods executes superclass
     Failure/Error: result.should eq(expected)

       expected: "Reference"
            got: "Object" # <<<<<<<<< got Object now, why?

     # spec/spec_helper.cr:269
```

Version: 0.20.3, 0.20.4, master
