### ISSUE TITLE
ICE Bug: `def refill_in_buffer [...]` in crystal/src/io/encoding.cr:123:13 has no type 

### ISSUE THREAD

**Issue by TechMagister** [crystal-lang/crystal#3946]
Crystal version : 
Crystal 0.20.4 [d1f8c42f8] (2017-01-27)
Crystal 0.20.5+2 [15032ccf2] (2017-01-27) 

Full stack trace and macro generated :
 https://gist.github.com/TechMagister/9f70c1fa0fa61a96a521f19336c61a0e

Code to reproduce ( sorry, I have no time to reduce this for the moment :/ ): 
https://github.com/TechMagister/cracker/tree/ice

**Comment by mverzilli** [comment]
Please if you find the time to write a reduced code snippet to reproduce it do so. It drastically increases the odds of having it fixed :).

**Comment by TechMagister** [comment]
Reduced code : 
```crystal
require "cli"
require "json"

class Command
    JSON.mapping({
      content: String
    })
end



class Main < Cli::Supercommand
    class Server < Cli::Command
      def run
        Command.from_json("")
      end
    end
end

Main.run ARGV
```

```yaml
shards:
  callback:
    github: mosop/callback
    version: 0.6.2

  cli:
    github: mosop/cli
    version: 0.6.4

  optarg:
    github: mosop/optarg
    version: 0.5.4

  string_inflection:
    github: mosop/string_inflection
    version: 0.2.0
```
