### ISSUE TITLE
OptionParser should allow flag with optional value

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5338]
In #4499 it has come up, that `OptionParser` does not allow for a flag wich could either be assigned a value (`--flag=value`) or not be used without value (`--flag`). In the references PR it happend that `--color a.cr` was misinterpreted as flag `--color` with value `a.cr`, whereas it is meant to be a value-less flag `--color` and an unnamed argument `a.cr`.

Currently, the format `--flag [value]` allows a flag value to be missing, but this only works if it is the last argument or the next argument is also a flag. It would also match an unnamed argument. There should be a way to prevent that.

Now, obviously, this can't work with an empty space as separater between flag an value as this would always be ambigous, but it would work if it was enforced to be an equals sign: `--foo arg` would be an value-less flag, `--flag=value` would be a flag with value `value`.

**Comment by MakeNowJust** [comment]
> this only works if it is the last argument or **the next argument is also a flag**.

It depends options handler order. For example:

```crystal
require "option_parser"

def parse(args)
  p [:parse, args]
  OptionParser.parse(args) do |opts|
    opts.on("-a [val]", "") do |val|
      p [:a, val]
    end

    opts.on("-b [val]", "") do |val|
      p [:b, val]
    end

    opts.unknown_args do |args|
      p [:unknown_args, args]
    end
  end
  puts
end

parse(%w(-a -b b))
# [:parse, ["-a", "-b", "b"]
# [:a, "-b"]
# [:unknown_args, ["b"]]

parse(%w(-b -a a))
# [:parse, ["-b", "-a", "a"]
# [:a, "a"]
# [:unknown_args, []]
# NOTE: why "-b" is not called?
```

**Comment by straight-shoota** [comment]
Wow, this looks like there are some serious issues with optional parameters.

**Comment by urde-graven** [comment]
This is patched in commit 0c306cad23f906d87a82ca667c862d3afde9011d, which fixes 4 issues - see new specs in this commit against crystal main branch: 

```
Failures:

  1) OptionParser optional option doesn't get separated value if specified with merged flag
     Failure/Error: flag.should eq(expect_value)

       Expected: ""
            got: "123"

     # spec/std/option_parser_spec.cr:15

  2) OptionParser optional option doesn't get separated value that looks like flag if specified with separated flag
     Failure/Error: flag.should eq(expect_value)

       Expected: ""
            got: "-g -h"

     # spec/std/option_parser_spec.cr:15

  3) OptionParser doesn't get value shifted in position because of removing another flag
     Failure/Error: flag.should eq(expect_value)

       Expected: ""
            got: "123"

     # spec/std/option_parser_spec.cr:15

  4) OptionParser should take short-flag's missing information about option from long flag
     Failure/Error: captured_z.should eq ""

       Expected: ""
            got: "14"

```

Three fixed problems are mentioned here - flag matched as optional value, separate argument matched when optional value is defined together with flag, and shifted argument matched as value because arguments were removed by previous matches. I also added improvement requested for example in #6632, because removing of consumed arguments is now additional work, but this is evidently done poorly to maintain backward compatibility - it should probably work like in Ruby's OptionParser, eg #parse should be non-destructive and #parse! should consume flags and their values: 

```
OptionParser.parse!
(from ruby core)
------------------------------------------------------------------------
  parse!(argv = default_argv, into: nil)

------------------------------------------------------------------------
Same as #parse, but removes switches destructively. Non-option arguments remain in argv.
```

But I would agree with https://github.com/crystal-lang/crystal/pull/4809#issuecomment-375487285, that optionparser needs a rewrite and this can be part of such work
