### ISSUE TITLE
PC crashes on running the following code under Windows 10 WSL - Kernel_security_check_failed 

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal#5569]
Here is a fun bug...

Code:
```
require "./temp/*"

require "kilt/slang"

require "baked_file_system"

class FileStorage
  BakedFileSystem.load("/mnt/d/Programming/Crystal/temp/src/resources")
end

path = "template.slang"
file_string = ""
file = nil
begin
  file = Fi'''leStorage.get(path)
rescue BakedFileSystem::NoSuchFileError
  puts "File #{path} is missing"
end
```
Note the ''' location next to FileStorage ( **file = Fi'''leStorage.get(path)** ). This crashes the system with a blue screen of dead and the above mentioned error  Kernel_security_check_failed.

Shard ( named temp ):
```
name: temp
version: 0.1.0

authors:
  -  <>

crystal: 0.24.1

license: MIT

dependencies:
  slang:
    github: jeromegn/slang
  kilt:
    github: jeromegn/kilt
  baked_file_system:
    github: schovi/baked_file_system    
```

OS and other information:
```
OS: Windows 10 - WSL ( Ubuntu 16.xx forgot exact version )
Crystal 0.24.1 (2017-12-22)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
Linux DESKTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Run:
```
@DESKTOP:/mnt/d/Programming/Crystal$ cd temp/
@DESKTOP:/mnt/d/Programming/Crystal/temp$ crystal src/temp.cr
Crash ...
```

Tried it multiple times, multiple crashes.

Yes, its nonsense to do that but i remember mistyping a few days ago and getting a blue screen of dead. Today i was able to trace back what i mistype. One expect a compile error, not taking down the entire PC.

Will answer tomorrow on questions, late here.
