### ISSUE TITLE
YAML doesn't correctly handle null types (since 0.24.x)

### ISSUE THREAD

**Issue by fgimian** [crystal-lang/crystal#6137]
Hey there guys, I've noticed a problem that was introduced in 0.24.x (works correctly in 0.23.1):

```crystal
require "yaml"
data = <<-END
         ---
         empty_value: null
         string: "123"
         integer: 123
         float: 123.45
         booleans: [yes, true, on, no, false, off]
         END
data = YAML.parse data
puts data.to_yaml
```

**Output (0.23.1)**:

```yaml
---
empty_value: null
string: 123
integer: 123
float: 123.45
booleans:
- yes
- true
- on
- no
- false
- off
```

**Output (0.24.2)**:

```yaml
---
empty_value: 
string: "123"
integer: 123
float: 123.45
booleans:
- true
- true
- true
- false
- false
- false
```

Notice the missing `null` in the `empty_value` item.  The booleans have also changed, but I have validated that Python's YAML parser also does this.
