### ISSUE TITLE
Adding an Array(Int32) field to a class breaks --release build

### ISSUE THREAD

**Issue by sci4me** [crystal-lang/crystal#7012]
Crystal 0.26.1 (2018-09-27)
LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu

I am running Antergos (Arch Linux).

I have the following code:
```crystal
require "sdl"

class Grid
  @rand = Random.new

  @grid : Array(Bool)
  @temp : Array(Bool)
  # @intensity : Array(Int32)

  def initialize(@grid_width : Int32, @grid_height : Int32)
    @grid = Array(Bool).new(@grid_width * @grid_height, false)
    @temp = Array(Bool).new(@grid.size, false)
    # @intensity = Array(Int32).new(@grid.size, 0)
    randomize
  end

  def randomize
    (0...@grid.size).each do |i|
      @grid[i] = @rand.next_bool
    end
  end
end

SDL.init(SDL::Init::VIDEO)
at_exit { SDL.quit }

window = SDL::Window.new("Life", 1280, 720)
renderer = SDL::Renderer.new(window, SDL::Renderer::Flags::ACCELERATED | SDL::Renderer::Flags::PRESENTVSYNC)
width, height = window.size

grid = Grid.new width, height

loop do
  case event = SDL::Event.poll
  when SDL::Event::Quit
    break
  when SDL::Event::Keyboard
    break
  end

  renderer.present
end
```
Here's my shard.yml:
```yaml
name: life.cr
version: 0.1.0

authors:
  - Scitoshi Nakayobro <matthewtpeterson1@gmail.com>

targets:
  kitty_clicker:
    main: src/life.cr

dependencies:
    sdl:
        github: ysbaddaden/sdl.cr

crystal: 0.26.1

license: MIT
```

If I uncomment the two commented lines, the program compiles and 'runs', but the window never opens. This only happens on a release build; without --release, it works fine. I haven't been able to get any kind of error out of it thus far.
