### ISSUE TITLE
CircleCI config on init tool

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#8532]
With the init tool, we have some great core functionality for any new Crystal app or lib, but it currently only supplies a travis example config. We don't even use travis for the language testing. I feel like this is something the language can easily provide since docker builds are automated.

I have drafted up an example `config.yml` for CircleCI based around [Circle's Public recommendation](https://github.com/CircleCI-Public/circleci-demo-crystal) for Crystal [here](https://gist.github.com/Daniel-Worrall/63603b9e9a91e7a8bf24f00cc9e2143c) without specs.

```yml
version: 2
jobs:
  build: 
    working_directory: ~/<%= config.name %>
    docker:
      - image: crystallang/crystal:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run: crystal spec
      - run: crystal tool format --check
```
