### ISSUE TITLE
Failing test: HTTP::Cookie::Parser expired? by max-age=0

### ISSUE THREAD

**Issue by deiv** [crystal-lang/crystal#9039]
Hi,

Running the spec for the std I get the next broken test:

```
Failures:

  1) HTTP::Cookie::Parser expired? by max-age=0
     Failure/Error: parse_set_cookie("bla=1; max-age=0").expired?.should eq true

       Expected: true
            got: false

     # spec/std/http/cookie_spec.cr:215
```
