### ISSUE TITLE
random segfaults when statically compiling on alpine

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#9160]
This has been happening maybe 1/5th of the time for me when statically compiling using the following alpine docker image ever since 0.34.0 dropped. With 0.33.0 this never happened. What I'm getting is an invalid memory access error at some random address. I'll update this with a printout of the error next time I see it.

This could be as simple as "give docker more RAM" in which case I'll close the issue.

```
FROM crystallang/crystal:0.34.0-alpine-build

RUN apk add --update --no-cache --force-overwrite openssl-libs-static \
  openssl-dev g++ gc-dev libc-dev libevent-dev libevent-static \
  libxml2-dev llvm llvm-dev llvm-static make pcre-dev readline-dev \
  readline-static yaml-dev zlib-dev zlib-static ca-certificates

CMD ["/bin/sh"]
```
Calling syntax:
```
docker run --rm -it -v $PWD:/app -w /app my-image:latest \
  crystal build src/app.cr -o bin/app --release --static --debug -Dproduction
```

The app in question is an amber app with the following shards installed:
```
dependencies:
  amber:
    github: amberframework/amber
    version: 0.34.0
    #branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.20.0

  pg:
    github: will/crystal-pg
    version: ~> 0.21.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: ~> 0.4.0

  validator:
    github: nicolab/crystal-validator
    version: 1.0.0-rc5

  raven:
    github: Sija/raven.cr

development_dependencies:
  garnet_spec:
    github: amberframework/garnet-spec
    version: 0.2.1
```

Again this only became an issue recently with the 0.34.0 release.

I don't really mind as I can just re-run the build, however I thought I'd let you guys know so we can document and possibly fix this down the road.
